version: '2'

services:
  nginx:
    container_name: homework-nginx
    build:
      context: ./nginx
      args:
        http_protocol: ${HTTP_PROTOCOL}
        server_name: ${SERVER_NAME}
    restart: always
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_HTTPS}:445"
    networks:
      - homework-network
    links:
      - php

  php:
    container_name: homework-php
    build: ./php
    restart: always
    volumes:
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php/cronlogs/cron.log:/var/log/cron.log
    ports:
      - '${PHP_PORT}:9000'
    networks:
      - homework-network
    links:
      - mysql
      - redis
      - es

  mysql:
    container_name: homework-mysql
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./mysql-files:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - homework-network

  redis:
    container_name: homework-redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:3389"
    networks:
      - homework-network

  es:
    container_name: homework-es
    image: elasticsearch:8.4.1
    restart: always
    environment:
      - discovery.type= single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "${ES_PORT}:9200"

networks:
  homework-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.16/28
